# Generated by Django 3.1.7 on 2021-06-29 11:55

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=255)),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('cor', models.CharField(max_length=10)),
                ('chassi', models.CharField(max_length=255, unique=True)),
                ('ano_fabricacao', models.IntegerField(validators=[django.core.validators.MinValueValidator(1940), core.models.max_value_current_year], verbose_name='ano_fabricacao')),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_compra', models.DateTimeField()),
                ('data_venda', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
