# Generated by Django 3.1.7 on 2021-06-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='data_compra',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='data_venda',
            field=models.DateField(blank=True, null=True),
        ),
    ]
