# Generated by Django 3.1.7 on 2021-06-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210629_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='valor_venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
