# Generated by Django 3.1.7 on 2021-06-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210629_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='chassi',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='placa',
            field=models.CharField(max_length=20),
        ),
    ]
